StockExchangeApp/Controllers/CompareController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using StockExchangeApp.BusinessLogic;
using StockExchangeApp.DatabaseClasses;
using StockExchangeApp.Models;

namespace StockExchangeApp.Controllers
{
    public class CompareController : Controller
    {
        private StockExchangeDBContext db = new StockExchangeDBContext();

        public ActionResult Index()
        {
            var model = new ComparePageViewModel();
            InitializeModelFields(model);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Amount,Interests,BeginDate,EndDate,SelectedCapitalization")] ComparePageViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            InitializeModelFields(model);

            var fund = new Fund(model.Amount, model.BeginDate, model.EndDate);

            model.StockRecords = fund.GetFundData();
            model.StockProfit = fund.GetProfit();
            var info = fund.GetInfo();
            foreach (var item in info)
            {
                model.Info.Add(item);
            }

            var deposit = new Deposit(int.Parse(model.SelectedCapitalization), model.Amount, model.Interests, model.BeginDate, model.EndDate);
            model.DepositRecords = deposit.GetDepositData();
            model.DepositProfit = deposit.GetProfit();
            info = deposit.GetInfo();
            foreach (var item in info)
            {
                model.Info.Add(item);
            }

            return View("Index", model);
        }

        private void InitializeModelFields(ComparePageViewModel model)
        {
            model.Capitalization = CreateCapitalizationList();
            model.Info = new List<string>();
            model.DepositRecords = new List<DataRecordViewModel>();
            model.StockRecords = new List<DataRecordViewModel>();
        }

        private List<SelectListItem> CreateCapitalizationList()
        {
            var capitalizations = Deposit.GetCapitalizations();

            var listItems = capitalizations.Select(capitalization => new SelectListItem()
            {
                Text = capitalization.Item1, Value = capitalization.Item2.ToString()
            }).ToList();

            listItems[0].Selected = true;
            return listItems;
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockExchangeApp/Controllers/StockRecordsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using StockExchangeApp.DatabaseClasses;

namespace StockExchangeApp.Controllers
{
    public class StockRecordsController : Controller
    {
        private StockExchangeDBContext db = new StockExchangeDBContext();

        // GET: StockRecords
        public ActionResult Index(int? page)
        {
            var pageSize = 50;
            var pageNumber = (page ?? 1);
            return View(db.StockRecords.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: StockRecords/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var stockRecord = db.StockRecords.Find(id);
            if (stockRecord == null)
            {
                return HttpNotFound();
            }
            return View(stockRecord);
        }

        // GET: StockRecords/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StockRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Data,Wartosc")] StockRecord stockRecord)
        {
            if (ModelState.IsValid)
            {
                db.StockRecords.Add(stockRecord);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stockRecord);
        }

        // GET: StockRecords/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var stockRecord = db.StockRecords.Find(id);
            if (stockRecord == null)
            {
                return HttpNotFound();
            }
            return View(stockRecord);
        }

        // POST: StockRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Data,Wartosc")] StockRecord stockRecord)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stockRecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stockRecord);
        }

        // GET: StockRecords/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var stockRecord = db.StockRecords.Find(id);
            if (stockRecord == null)
            {
                return HttpNotFound();
            }
            return View(stockRecord);
        }

        // POST: StockRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var stockRecord = db.StockRecords.Find(id);
            db.StockRecords.Remove(stockRecord);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockExchangeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/chartjs")
        @Scripts.Render("~/bundles/dateValidation")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StockExchangeApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Wszystkie dane", "Index", "StockRecords", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Porównaj", "Index", "Compare", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>